
# POST http://localhost:3000/api/admin/register
# Content-Type: application/json

# {
#   "username": "kimkoe",
#   "email": "kimenyujoseph@gmail.com",
#   "password": "example_password",
#   "phoneNum": "+254712349673"
# }

# POST http://localhost:3000/api/admin/verify
# Content-Type: application/json

# {
#   "email": "kimenyujoseph@gmail.com",
#   "verificationCode": "35485"
# }


# POST http://localhost:3000/api/customer/login
# Content-Type: application/json

# {
#   "username": "kimenyu",
#   "password": "example_password"
# }

### Request with Bearer Token



DELETE  http://localhost:3000/api/orders/65f35b3c2177f18ef9834476
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWYyODRhOGQ4YTAyMmYyODVmNWE5NGIiLCJ1c2VyRW1haWwiOiJraW1lbnl1am9zZXBoNzNAZ21haWwuY29tIiwiaWF0IjoxNzEwNDg1MDU0LCJleHAiOjE3MTA0ODg2NTR9.Jr33Htr_ETjbcI3oYUJAOKL8I83Uz8FfqhXTaCsXVe0

# {
#     "meals": [
#         {
#             "meal_id": "65f2a39e03bac90a68240d20",
#             "quantity": 5
#         },
#         {
#             "meal_id": "65f2a3c203bac90a68240d23",
#             "quantity": 3
#         }
#     ]
# }



# POST http://localhost:3000/api/restaurant/create
# Content-Type: application/json

# {
#   "name": "Pizza hut",
#   "description": "best pizza place",
#   "address": "Rongai",
#   "image": "pizzahut.png",
#   "owner": "65f295731bd4780773511a77"
# }

# GET  http://localhost:3000/api/restaurant

# DELETE   http://localhost:3000/api/restaurant/65f298491bd4780773511a81
# Content-Type: application/json

# {
#   "name": "Pizza hut updated",
#   "description": "best pizza place",
#   "address": "Rongai",
#   "image": "pizzahut.png",
#   "owner": "65f295731bd4780773511a77"
# }

# POST http://localhost:3000/api/meal/create
# Content-Type: application/json

# {
#   "name": "Pizza hut pizza",
#   "price": 1100,
#   "description": "Taste the best pizza from Pizza hut",
#   "image": "pizza.png",
#   "restaurant": "65f297841bd4780773511a7e"
# }

# GET  http://localhost:3000/api/meal/all

# PUT  http://localhost:3000/api/meal/update/65f2a39e03bac90a68240d20
# Content-Type: application/json

# {
#   "name": "Coffee",
#   "price": 250,
#   "description": "Taste the best coffe",
#   "image": "coffee.png"
# }
