
# POST http://localhost:3000/api/admin/register
# Content-Type: application/json

# {
#   "username": "admin",
#   "email": "mbuguakimenyu@gmail.com",
#   "password": "example_password",
#   "phoneNum": "+254793058969"
# }

# POST http://localhost:3000/api/admin/verify
# Content-Type: application/json

# {
#   "email": "mbuguakimenyu@gmail.com",
#   "verificationCode": "10120"
# }


# POST http://localhost:3000/api/customer/login
# Content-Type: application/json

# {
#   "username": "kim",
#   "password": "example_password"
# }

### Request with Bearer Token



# DELETE  http://localhost:3000/api/orders/65f35b3c2177f18ef9834476


# POST http://localhost:3000/api/order/dispatch/65f3f88b8877e0b444994c72

# GET http://localhost:3000/api/users/my-orders

POST http://localhost:3000/api/order/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWY0OGI0YmU5MWY5MDNmOGY5MzU5MTYiLCJ1c2VyRW1haWwiOiJraW1lbnl1am9zZXBoNzNAZ21haWwuY29tIiwicm9sZSI6ImN1c3RvbWVyIiwiaWF0IjoxNzEwNTczNjU4NTA0LCJleHAiOjE3MTA1NzQyNjMzMDR9.8OZFfqGo7MuQNWWn6zyg2znU0td4AlWNo_EbCxDycz0

{
  "meals": [
    {
      "meal_id": "65f4c01cbd74a0be2c49bd48",
      "quantity": 3
    },
    {
      "meal_id": "65f4c19cbd74a0be2c49bd4e",
      "quantity": 4
    },
    {
      "meal_id": "65f4c1babd74a0be2c49bd51",
      "quantity": 3
    }
  ]
}

# GET http://localhost:3000/api/restaurants/65f297841bd4780773511a7e/orders



# POST http://localhost:3000/api/restaurant/create
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWY0YjkzN2JkNzRhMGJlMmM0OWJkNDEiLCJ1c2VyRW1haWwiOiJtYnVndWFraW1lbnl1QGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcxMDU3MjM2MDczNywiZXhwIjoxNzEwNTcyOTY1NTM3fQ.kPXYOTunvEMx7KubqAvvJ8zI9for--ldEWjYio-2YSw

# {
#   "name": "chafua foodplace",
#   "description": "This is where the best chafua resides",
#   "address": "Rongai",
#   "image": "chafua.png",
#   "owner": "65f4b937bd74a0be2c49bd41"
# }

# GET  http://localhost:3000/api/restaurant

# DELETE   http://localhost:3000/api/restaurant/65f298491bd4780773511a81
# Content-Type: application/json

# {
#   "name": "Pizza hut updated",
#   "description": "best pizza place",
#   "address": "Rongai",
#   "image": "pizzahut.png",
#   "owner": "65f295731bd4780773511a77"
# }

# POST http://localhost:3000/api/meal/create
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWY0YjkzN2JkNzRhMGJlMmM0OWJkNDEiLCJ1c2VyRW1haWwiOiJtYnVndWFraW1lbnl1QGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcxMDUzNzA4NzMyMiwiZXhwIjoxNzEwNTM3NjkyMTIyfQ.qn4K53_RP56TAPbG_0TS2IDgL0OpylDfVhs8dfojS9o

# {
#   "name": "The beef pizza",
#   "price": 950,
#   "description": "Taste the best pizza from beef pizza",
#   "image": "pizza.png",
#   "restaurant": "65f4befdbd74a0be2c49bd46"
# }

# GET  http://localhost:3000/api/meal/all

# PUT  http://localhost:3000/api/meal/update/65f2a39e03bac90a68240d20
# Content-Type: application/json

# {
#   "name": "Coffee",
#   "price": 250,
#   "description": "Taste the best coffe",
#   "image": "coffee.png"
# }
